const parts=[{name:'문장 읽기',qs:[1,2],prep:45,answers:[45,45],hint:'지문을 확인하고 소리 내어 읽을 준비를 하세요.'},{name:'사진 묘사',qs:[3,4],prep:45,answers:[30,30],hint:'사진 속 장소, 사람, 행동을 정리하세요.'},{name:'질문에 답하기',qs:[5,6,7],prep:3,answers:[15,15,30],hint:'질문에 맞는 답변을 준비하세요.'},{name:'정보 활용하기',qs:[8,9,10],prep:3,answers:[15,15,30],hint:'제공된 정보에서 답변에 필요한 내용을 찾으세요.'},{name:'의견 제시하기',qs:[11],prep:45,answers:[60],hint:'의견과 이를 뒷받침할 이유를 정리하세요.'}];
function makeSequence(mode){let result=[];parts.forEach((p,i)=>{if(mode!=='all'&&Number(mode)!==i)return;if(i===3)result.push({part:i,q:8,type:'read',duration:45});p.qs.forEach((q,j)=>{result.push({part:i,q,type:'prep',duration:p.prep},{part:i,q,type:'answer',duration:p.answers[j]})})});return result}
const $=id=>document.getElementById(id);let sequence=makeSequence('all'),index=0,left=sequence[0].duration*1000,running=false,done=false,deadline=0,audio;
const phaseName=t=>t==='read'?'지문 읽기':t==='prep'?'준비 시간':'답변 시간';
function beep(){if(!$('sound').checked||!audio)return;try{const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=sequence[index]?.type==='answer'?880:660;g.gain.setValueAtTime(.12,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.35);o.start();o.stop(audio.currentTime+.35)}catch{}}
function announce(){const s=sequence[index];$('announce').textContent=done?'연습이 완료되었습니다.':`Q${s.q}, ${phaseName(s.type)}, ${s.duration}초`}
function render(){const s=sequence[index],p=parts[s.part];$('panel').classList.toggle('answer',s.type==='answer'&&!done);$('question').textContent=s.type==='read'?'QUESTIONS 08–10 · 지문':`QUESTION ${String(s.q).padStart(2,'0')} / 11`;$('status').textContent=done?'완료':running?'진행 중':left===s.duration*1000?'시작 전':'일시정지';$('phase').textContent=done?'연습 완료':phaseName(s.type);$('title').textContent=done?'수고하셨습니다!':p.name;let sec=Math.ceil(left/1000);$('clock').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;$('hint').textContent=done?'처음부터 다시 시작하거나 다른 파트를 선택해 연습하세요.':s.type==='read'?'스케줄표나 안내 양식의 정보를 45초 동안 읽으세요.':s.type==='answer'?'지금 소리 내어 답변하세요.':p.hint;$('fill').style.width=`${done?0:left/(s.duration*1000)*100}%`;$('start').textContent=done?'다시 연습':running?'일시정지':left===s.duration*1000&&index===0?'연습 시작':'계속하기';$('skip').disabled=done;const n=sequence[index+1];$('next').textContent=done?'연습 종료':n?`${n.type==='read'?'Q8–10':`Q${n.q}`} ${phaseName(n.type)} · ${n.duration}초`:'연습 완료';let rem=done?0:Math.ceil(left/1000)+sequence.slice(index+1).reduce((sum,s)=>sum+s.duration,0);$('remaining').textContent=`${Math.floor(rem/60)}분 ${String(rem%60).padStart(2,'0')}초`;$('steps').textContent=`${done?sequence.length:index+1} / ${sequence.length} 단계`;document.querySelectorAll('.part').forEach(el=>el.classList.toggle('active',!done&&Number(el.dataset.part)===s.part))}
function reset(){running=false;done=false;index=0;sequence=makeSequence($('mode').value);left=sequence[0].duration*1000;render();announce()}
function advance(){if(index+1===sequence.length){done=true;running=false;left=0}else{index++;left=sequence[index].duration*1000}announce()}
function tick(now=performance.now()){if(!running)return;while(running&&now>=deadline){advance();beep();if(running)deadline+=left}if(running)left=Math.max(0,deadline-now);render()}
$('start').onclick=()=>{if(done)reset();if(running){tick();running=false}else{try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume()}catch{}deadline=performance.now()+left;running=true;announce()}render()};$('reset').onclick=reset;$('skip').onclick=()=>{advance();if(running)deadline=performance.now()+left;beep();render()};$('mode').onchange=reset;document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['BUTTON','SELECT','INPUT'].includes(document.activeElement.tagName)){e.preventDefault();$('start').click()}});document.addEventListener('visibilitychange',()=>tick());setInterval(tick,50);render();
